mongodb:
  username: "![04Qb6Uw9SaPQc8uixMzYKA==]"
  password: "![Qyz82flkLtmtcjDXOwHDydY9uRzYYoCV]"
anypoint:
  mq:
    client_id: "![QTDPYb74PrrRwUvE7SP+3qqEIMT9fdjG36nZiy+SZA9RGu92s4KMjQ==]"
    client_secret: "![ovvRnx9E2e2i2YTsnRLxrvjpRJ680nvm22ZW7ePx0EnhcDegUuByvg==]"