mongodb:
  username: "![oIKmhMR8oEm8laAdtT5ibw==]"
  password: "![BM5XuiW1IgARWDD/MhR0XZxuYYSNrsIU]"
anypoint:
  mq:
    client_id: "![QTDPYb74PrrRwUvE7SP+3qqEIMT9fdjG36nZiy+SZA9RGu92s4KMjQ==]"
    client_secret: "![ovvRnx9E2e2i2YTsnRLxrvjpRJ680nvm22ZW7ePx0EnhcDegUuByvg==]"