mongodb:
  database: "fhir-dev"
anypoint:
  autodiscovery: "16485168"
  mq:
    destination: "fhir-bulk-data-jobs"
resourceTypes: "Patient,Organization,Encounters,Location,Practitioner,PractitionerRole"